CREATE TABLE USERS (ID INTEGER NOT NULL, LOGIN VARCHAR(256) NOT NULL, PASSWORD VARCHAR(256) NOT NULL, LASTNAME VARCHAR(265) NOT NULL, FIRSTNAME VARCHAR(256) NOT NULL, BUYER BOOLEAN DEFAULT false  NOT NULL, CB INTEGER, ADDRESS VARCHAR(256), PRIMARY KEY (ID));

CREATE TABLE ARTICLES (ID INTEGER NOT NULL, LABEL VARCHAR(256) NOT NULL, STARTINGPRICE DOUBLE NOT NULL, DESCRIPTION VARCHAR(256), CATEGORIES VARCHAR(2048), DEADLINE DATE NOT NULL, ACTIF BOOLEAN DEFAULT true  NOT NULL, IDENCHEREMAX INTEGER, IDUSER INTEGER NOT NULL, PAID BOOLEAN DEFAULT false  NOT NULL, PRIMARY KEY (ID));

CREATE TABLE ENCHERES (ID INTEGER NOT NULL, IDARTICLE INTEGER NOT NULL, IDUSER INTEGER NOT NULL, PROPOSITION DOUBLE NOT NULL, IDLASTENCHERE INTEGER NOT NULL, PRIMARY KEY (ID));

CREATE TABLE PROMOTIONS (ID INTEGER NOT NULL, NBMINARTICLES INTEGER NOT NULL, CODE VARCHAR(4) NOT NULL, ACTIVE BOOLEAN DEFAULT false  NOT NULL, PRIMARY KEY (ID));


